import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="font-inter min-h-screen bg-[#f0f0f0]">
      <Head>
        <title>E-Monev Kab. Bojonegoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-e-monev.png" />
      </Head>
      <header className='bg-[#f0f0f0] py-4 2xl:px-64 px-44 flex gap-4 items-center'>
        <Link href="/" className='flex gap-4 items-center'>
          <Image src={'/logo-e-monev.png'} height={50} width={50} alt="logo" />
          <h1 className='text-xl font-semibold text-gray-700 hover:text-black'>E-Monev | Pemerintah Kabupaten Bojonegoro</h1>
        </Link>
      </header>
      <div className='p-2'></div>
      <main className="2xl:px-64 px-44 py-4 flex items-center justify-between">
        <div className='h-full mx-auto w-full flex-1 justify-center'>
          <h1 className='text-[40px] font-bold font-poppins'>E-Monev</h1>
          <div className='p-4'></div>
          <p className='font-semibold text-justify'>
            E-Monev merupakan Sistem Informasi yang digunakan untuk memfasilitasi Perangkat Daerah dalam membuat Laporan Monitoring Realisasi Fisik dan Keuangan APBD dan Evaluasi RENJA/RKPD
          </p>
          <div className='p-4'></div>
          <Link href='/login' className='bg-primary text-white font-semibold px-3 py-2 rounded-[4px] shadow-md hover:opacity-80 transform transition-all duration-200'>LOGIN</Link>
        </div>
        <div className='flex-1'>
          <Image src='/hero.jpg' alt="" width={1000} height={1000} />
        </div>
      </main>
      <footer className='fixed bottom-0 2xl:px-64 px-44 py-8 w-full bg-[#f0f0f0]'>
        <div className='flex items-center'>
          <h1 className='font-bold text-base'>2022 &copy; Bappeda Kabupaten Bojonegoro</h1>
        </div>
      </footer>
    </div>
  )
}
